Add a failure point for unknowns.

diff --git a/night-uploader b/night-uploader
--- a/night-uploader
+++ b/night-uploader
@@ -229,6 +229,9 @@ then
   # Media pages
   makeIndex
   cleanUp
+else
+  echo "$fail Unknown workflow ID $runType."
+  exit 1
 fi
   
 echo "$ok Finished workflow ID $runType."
