Add more startup checks including a check to make sure AWS is not already running.

diff --git a/night-uploader b/night-uploader
--- a/night-uploader
+++ b/night-uploader
@@ -42,13 +42,44 @@ then
   exit 1
 fi
 
-# Check for AWS ClI
+# Check for AWS CLI
 which aws > /dev/null
 checkForAWS=$?
 if [[ "$checkForAWS" != "0" ]]
 then 
   echo "You need AWS CLI to run this script."
   exit 1
+fi
+
+# Check for variables set correctly
+if [[ "$location" == "" ]] && [[ "$s3bucket" == "" ]] && [[ "$endLocation" == "" ]] && [[ "$templateLocation" == "" ]] && [[ "$indexFile" == "" ]] && [[ "$indexFileLoc" == "" ]] && [[ "$listingFile" == "" ]] && [[ "$listingFileLoc" == "" ]] && [[ "$newUploadsFile" == "" ]] && [[ "$newUploadsFileLoc" == "" ]] && [[ "$curTime" == "" ]]
+then
+  echo "You have not set all the required variables in the variables block. Please edit them with the correct details."
+  exit 1
+fi
+
+# Check if locations and files exist.
+if ! [[ -d "$location" ]] && ! [[ -d "$endLocation" ]] && ! [[ -d "$templateLocation" ]] && ! [[ -r "$templateLocation""afterlist" ]] && ! [[ -r "$templateLocation""footer" ]] && ! [[ -r "$templateLocation""head" ]]
+then
+  echo "One or more of the folders and/or files does not exist."
+  exit 1
+fi
+
+# Check if AWS is running already
+retryCount=0
+while ps aux | grep -v grep | grep "aws" > /dev/null
+do
+  if [[ "$retryCount" == 0 ]]
+  then
+    echo "AWS is currently running. Waiting for AWS to finish to avoid issues."
+  fi
+  echo -n "."
+  retryCount=$((retryCount+1))
+  sleep 5
+done
+if [[ "$retryCount" != 0 ]]
+then
+  echo
 fi
 
 
